ALTER TABLE interactions ADD COLUMN IF NOT EXISTS is_task BOOLEAN DEFAULT FALSE;
ALTER TABLE interactions ADD COLUMN IF NOT EXISTS is_done BOOLEAN DEFAULT FALSE;
ALTER TABLE interactions ADD COLUMN IF NOT EXISTS due_date TIMESTAMP WITH TIME ZONE;
